### ISSUE TITLE
HTTP/2 version support

### ISSUE THREAD

**Issue by sergiobortsov** [cecilphillip/yarp-samples#5]
Hello Cecil
Sorry for bothering you, as I'm not actually a developer, but as DevOps I would like to use your LoadBalancer example in my infrastructure to balance the GRPC calls. And as you know it's possible only on HTTP/2. Is it possible to add to your LBProxy web app the HTTP/2 support? Or maybe it's already there and I missed something?
I'll be grateful for your comment and help.
Thanks

**Comment by sergiobortsov** [comment]
Sorry, I figured out by myself
Thanks

**Comment by cecilphillip** [comment]
Ok Sure. Glad you worked it out
