### ISSUE TITLE
Proxy not working?

### ISSUE THREAD

**Issue by jbonnett92** [cecilphillip/yarp-samples#9]
Hi,
I loaded up the project "CodeConfigSample"

As you can see I do have the items api loaded:
<img width="1440" alt="Screenshot 2023-01-25 at 01 46 21" src="https://user-images.githubusercontent.com/3740700/214462154-487d89f2-6773-403c-b228-588bd9ab2544.png">

I also get routes from `http://0.0.0.0:5000/yarp/routes`.

So why do I get a 404 when trying to access `http://0.0.0.0:5000/api/items`?

Thanks,
Jamie

**Comment by cecilphillip** [comment]
should be fixed now
